Server factory integration
moscajs/aedes-protocol-decoder pull request #5
Opened 2020-10-14 13:11 UTC by getlarge

- Refactor the protocol decoder 
  - change expected arguments ( to be used by `aedes-server-factory` )
  - split in several sub functions
  - export `extractSocketDetails` function, usable when not using / or trusting proxy

- Update test, docs, examples and dependancies

related to [aedes-changes](https://github.com/moscajs/aedes/pull/549) and [aedes-server-factory](https://github.com/moscajs/aedes-server-factory/pull/2)

2020-10-14 13:59 UTC, robertsLando commented on README.md
> +var server = createServer({ trustProxy: true, protocolDecoder }, broker.handle)
Once implemented in the factory remember to update the signature here too :)

2020-10-14 15:24 UTC, robertsLando requested changes

2020-10-14 15:24 UTC, robertsLando commented on README.md
> +The function extract socket details and if aedes-server-factory `trustProxy` option is set to true, it will first parse http headers (x-real-ip | x-forwarded-for) and proxy protocol (v1 and v2) to re
```suggestion
The function extract socket details and if aedes-server-factory `trustProxy` option is set to true, it will first parse http headers (x-real-ip | x-forwarded-for) and proxy protocol (v1 and v2) to retrieve information in `client.connDetails`.
```

2020-10-14 15:24 UTC, robertsLando commented on README.md
> +The function `protocolDecoder` and `extractSocketDetails` returns [ConnectionDetails](./types/index.d.ts), if the object contains data property, it will be parsed as an mqtt-packet.
```suggestion
The function `protocolDecoder` and `extractSocketDetails` returns [ConnectionDetails](./types/index.d.ts), if the object contains `data` property, it will be parsed as an mqtt-packet.
```

2020-10-14 15:24 UTC, robertsLando commented on README.md
> +The function `protocolDecoder` and `extractSocketDetails` returns [ConnectionDetails](./types/index.d.ts), if the object contains data property, it will be parsed as an mqtt-packet.
Also add a link to [mqtt-packet]()

2020-10-15 06:43 UTC, getlarge commented on README.md
> +The function `protocolDecoder` and `extractSocketDetails` returns [ConnectionDetails](./types/index.d.ts), if the object contains data property, it will be parsed as an mqtt-packet.
Why and where a link to mqtt packet?

2020-10-15 07:29 UTC, robertsLando commented on README.md
> +The function `protocolDecoder` and `extractSocketDetails` returns [ConnectionDetails](./types/index.d.ts), if the object contains data property, it will be parsed as an mqtt-packet.
@getlarge https://github.com/mqttjs/mqtt-packet where you mention mqtt-packet at the end of the paragrafer :)

2020-10-15 08:41 UTC, robertsLando commented on test.js
>    function finish () {
I would suggest to create a general `setup(options)` function that inits and returns `setup = { server, client, broker }` and a general `close(setup)` function to be called instead of `finish` like `t.tearDown(close.bind(t, setup))`

2020-10-15 08:49 UTC, robertsLando commented
```js
function setup(options){
var broker;
var server;
var client;

 if(options.broker) {
 broker = aedes({
    preConnect: options.broker.preConnect
  })
}

if(options.client) {
 client = mqtt.connect(options.client)
}

if(server) {
  server = createServer(broker,options.server)
}

return {broker, client, server};
}

function close(setup) {
 if(client) client.end(true)
 if(broker) broker.close()
 if(server) server.close()
}

test('tcp clients have access to the ipAddress from the socket', function (t) {
  t.plan(2)

var setup = setup(....)

// code here 

t.tearDown(close.bind(t, setup);
})
```

2020-10-26 10:21 UTC, robertsLando commented
@getlarge seems tests are endless on nodejs 12 /14

2020-10-26 10:49 UTC, getlarge commented
@robertsLando yes i noticed, but what i don't understand is that prior to this [commit](https://github.com/moscajs/aedes-protocol-decoder/pull/5/commits/53069088a7bec0c5b019dae1990efc0be71667ae), it was only node v10 which was hanging.

2020-10-26 10:50 UTC, getlarge commented
Also i tried to run tests locally with node v12 and this issue does not appear, so i'm kind of stuck with this right now.

2020-10-26 10:55 UTC, robertsLando commented
@getlarge From my experience with github actions, when weird things happen in tests the best is to disable parallel. LEt's see how this goes :) (already submitted a commit)

2020-10-26 10:59 UTC, robertsLando commented
@getlarge Seems stucked anyway. It stops here

```
# tcp proxied (protocol v1) clients buffer contains MQTT packet and proxy header
ok 15 no error
ok 16 no error
ok 17 should be equal
```

2020-10-26 11:00 UTC, robertsLando commented
@mcollina Is there any change in nodejs 10 to 12-14 that could cause this stuck in tests?

2020-10-26 11:03 UTC, getlarge commented
The last test in this suite is rather tricky because there are "many" sockets opened, since i tried to reproduce the behavior of a setup with a "real" proxy server.
So maybe a client | server connection could not be closed properly when test is ending ?

2020-10-26 11:06 UTC, robertsLando commented
@getlarge Maybe I got it. I think it could be caused by some leaked handler (open socket). I suggest you to edit your tests in a way that close waits for close callbacks before calling end. 

```
function close(setup, t) {

var toClose = 0
var closed = 0
 if(client) {
toClose++
client.end(true, onDone)
}
 if(broker) {
toClose++
broker.close(onDone)
}
 if(server) {
toClose++
server.close(onDone)
}

function onDone() {
if(toClose === ++closed) {
t.end()
}

}
```

2020-10-26 11:07 UTC, getlarge commented
I will try.
What's really curious, is that the tests work locally with node v12.3.0 but not 12.19.0 (which is the version used in the CI).

2020-10-26 11:08 UTC, robertsLando commented
Also what you could try to do is to create a custom server destroy method as server.close never triggers the callback if there are opened sockets. Or you could you this module: https://github.com/isaacs/server-destroy

2020-10-26 11:09 UTC, robertsLando commented
> What's really curious, is that the tests work locally with node v12.3.0 but not 12.19.0 (which is the version used in the CI).

No clue why but if test never ends just means some socket is left opened. So use this strategy and we will for sure find what's wrong here :)

2020-10-26 11:25 UTC, getlarge commented
The destroy method did not help, but it seems the error is caused by this block

```js
  socket.on('end', function (data) {
    proxyClient.end(data, function () {
      proxyClient.connected = false
    })
  })
```

When commented the test end properly.

2020-10-26 11:32 UTC, getlarge commented
@robertsLando Any idea what that error means at coverall parallel phase ?

2020-10-26 11:37 UTC, robertsLando commented
No clue but try to re enable parallel, that wasn't the problem

2020-10-26 12:46 UTC, robertsLando commented
@getlarge lol, a typo :)

2020-10-26 12:47 UTC, robertsLando commented
> When commented the test end properly.

If it's not needed, remove it

2020-10-26 12:57 UTC, mcollina commented on index.js
> +  }
I would recommend using `...` so much, it's expensive.

2020-10-26 13:06 UTC, robertsLando commented
Aedes 0.44.0 is on npm

2020-10-26 13:35 UTC, getlarge commented on index.js
> +  }
I suppose you meant that you "would not recommend",  so we should reassign `proto` properties manually instead ?

2020-10-26 13:39 UTC, getlarge commented on index.js
> +  }
something like this ?

```js
function extractSocketDetails (socket, proto) {
  if (socket._socket && socket._socket.address) {
    proto.isWebsocket = true
    proto.ipAddress = socket._socket.remoteAddress
    proto.port = socket._socket.remotePort
    proto.serverIpAddress = socket._socket.address().address
    proto.ipFamily = getProtoIpFamily(socket._socket.remoteFamily)
  } else if (socket.address) {
    proto.ipAddress = socket.remoteAddress
    proto.port = socket.remotePort
    proto.serverIpAddress = socket.address().address
    proto.ipFamily = getProtoIpFamily(socket.remoteFamily)
  }
  return proto
}
```

2020-10-27 07:10 UTC, robertsLando commented on index.js
> +  }
@getlarge Yes go for it

2020-10-27 08:23 UTC, robertsLando reviewed
@getlarge is websocket-stream still needed?

Also in packet.json `engines` set node >= 10

2020-10-27 08:23 UTC, robertsLando commented on package.json
> +    "websocket-stream": "^5.5.2"
@getlarge is websocket-stream still needed?

2020-10-27 08:23 UTC, robertsLando commented on package.json
>  }
in engines set node >= 10

2020-10-27 08:29 UTC, getlarge commented on package.json
> +    "websocket-stream": "^5.5.2"
good point, not needed anymore

2020-10-27 08:45 UTC, robertsLando approved these changes
LGTM

2020-10-27 14:19 UTC, mcollina approved these changes
lgtm

2020-10-27 14:24 UTC, merged

2020-10-27 14:25 UTC, robertsLando commented
@getlarge Should I release a 2.0.0?

2020-10-27 18:08 UTC, getlarge commented
@robertsLando If we strictly follow the semver, then yes you should probably go straight to 2.0.0.

2020-10-28 13:29 UTC, robertsLando commented
@getlarge Sorry for the delay, published on npm now