Added mTLS Decoder
moscajs/aedes-protocol-decoder pull request #8
Opened 2021-05-19 10:45 UTC by ayushsharma82

- [x] Add Decoder Code
- [ ] Update Readme of aedes-server-factory

Added Mutual TLS Decoder. This will specifically extract your client's certificate from TCP socket and add it to `client.connDetails.cert`.

You can also use `client.connDetails.certAuthorized` to see if certificate presented by client is valid or not.

Example code published in https://github.com/moscajs/aedes-server-factory/issues/3#issuecomment-843973539

2021-05-19 11:47 UTC, robertsLando requested changes

2021-05-19 11:47 UTC, robertsLando commented on index.js
> +  if(clientCert !== {} && clientCert !== null && clientCert !== undefined){
Based on nodejs docs this could just return null or an empty object, checking it is not undefined is useless. I also think that the entire method is useless and I would just set the cert to 

`proto.cert = socket.getPeerCertificate(true)`

2021-05-19 11:52 UTC, ayushsharma82 commented on index.js
> +  if(clientCert !== {} && clientCert !== null && clientCert !== undefined){
Hmm. I didn't really gave much thought to it. You can modify the PR accordingly.

2021-05-19 13:12 UTC, robertsLando requested changes

2021-05-19 13:12 UTC, robertsLando commented on index.js
> +}
```suggestion
```

2021-05-19 13:12 UTC, robertsLando commented on index.js
> +    proto.cert = getTlsClientCertificate(socket._socket)
```suggestion
    proto.cert = socket._socket.getPeerCertificate(true)
```

2021-05-19 13:12 UTC, robertsLando commented on index.js
> +    proto.cert = getTlsClientCertificate(socket)
```suggestion
    proto.cert = socket.getPeerCertificate(true)
```

2021-05-19 13:26 UTC, robertsLando requested changes
This also requires lint issues to be fixed and also types and docs

2021-05-20 07:06 UTC, getlarge requested changes
@ayushsharma82 That's a nice contribution, finally we will be able to use TLS easily with Aedes.

2021-05-20 07:06 UTC, getlarge commented on types/index.d.ts
> +  cert: any,  // getPeerCertificate can return an empty object or null
@ayushsharma82 could you set a more accurate type union then you could also remove the comment ?
Something like `PeerCertificate | {} | null`

2021-05-20 07:13 UTC, ayushsharma82 commented
I'm not that proficient in TypeScript. I'll leave this PR up to you guys now to make the necessary changes.

Thanks for the awesome package.

2021-05-20 07:56 UTC, robertsLando commented on types/index.d.ts
> +  cert: any,  // getPeerCertificate can return an empty object or null
Make a commit suggestion and merge it so we can merge this PR :)

2021-05-29 14:38 UTC, ayushsharma82 commented on types/index.d.ts
> +  cert: any,  // getPeerCertificate can return an empty object or null
Don't delay it this much guys :)

2021-05-31 07:28 UTC, robertsLando commented
@ayushsharma82 Please fix the missing things so we can merge this

2021-05-31 14:48 UTC, ayushsharma82 commented
@robertsLando  As I said, I don't use Typescript. It would be best for you guys to adapt the code according to your repo and typescript conformation.

2021-06-01 06:20 UTC, robertsLando commented
@getlarge Could you sort this

2021-06-01 07:30 UTC, getlarge commented
@robertsLando I will try by the end of the week.

2021-06-28 16:00 UTC, closed without merging